# Generated by Django 4.2.1 on 2023-07-10 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user_member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('passwrd', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=255)),
                ('phoneNumber', models.CharField(max_length=50)),
            ],
        ),
    ]
