# Generated by Django 4.2.1 on 2023-07-11 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('b_id', models.AutoField(primary_key=True, serialize=False)),
                ('b_name', models.CharField(max_length=255)),
                ('b_image', models.FileField(default=None, upload_to='brands/')),
            ],
        ),
    ]
