# Generated by Django 4.0.3 on 2023-07-17 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0002_brand'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('t_id', models.AutoField(primary_key=True, serialize=False)),
                ('t_name', models.CharField(max_length=255)),
                ('t_email', models.CharField(max_length=255)),
                ('t_description', models.CharField(max_length=255)),
                ('t_rating', models.CharField(max_length=255)),
                ('t_isActive', models.BooleanField()),
            ],
        ),
    ]
