# Generated by Django 4.0.3 on 2023-07-31 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0003_testimonial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('c_id', models.AutoField(primary_key=True, serialize=False)),
                ('c_name', models.CharField(max_length=255)),
                ('c_email', models.CharField(max_length=255)),
                ('c_desc', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='t_email',
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='t_name',
        ),
        migrations.AddField(
            model_name='testimonial',
            name='u_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
