# Generated by Django 4.0.3 on 2023-07-31 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0004_contactus_remove_testimonial_t_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('v_id', models.AutoField(primary_key=True, serialize=False)),
                ('v_name', models.CharField(max_length=255)),
                ('v_description', models.CharField(max_length=255)),
                ('v_bodyType', models.CharField(max_length=255)),
                ('v_brand', models.CharField(max_length=255)),
                ('v_fuelType', models.CharField(max_length=255)),
                ('v_engine', models.CharField(max_length=255)),
                ('v_powerWindow', models.BooleanField()),
                ('v_bluetooth', models.BooleanField()),
                ('v_keylessStart', models.BooleanField()),
                ('v_cruiseControl', models.BooleanField()),
                ('v_navigation', models.BooleanField()),
                ('v_heatedSeats', models.BooleanField()),
                ('v_image', models.FileField(default=None, upload_to='VehicleImages/')),
            ],
        ),
    ]
