# Generated by Django 4.0.3 on 2023-07-31 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0005_vehicle'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='v_price',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='v_brand',
            field=models.IntegerField(),
        ),
    ]
