# Generated by Django 4.0.3 on 2023-07-31 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0006_vehicle_v_price_alter_vehicle_v_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='v_brand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MyApp.brand'),
        ),
    ]
