# Generated by Django 4.0.3 on 2023-08-02 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0007_alter_vehicle_v_brand'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('s_id', models.AutoField(primary_key=True, serialize=False)),
                ('s_email', models.CharField(max_length=255)),
            ],
        ),
    ]
