# Generated by Django 4.0.3 on 2023-08-03 03:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0008_subscriber'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingInfo',
            fields=[
                ('b_id', models.AutoField(primary_key=True, serialize=False)),
                ('b_date', models.DateTimeField()),
                ('b_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MyApp.user_member')),
                ('b_vehicle', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MyApp.vehicle')),
            ],
        ),
    ]
