# Generated by Django 4.0.3 on 2023-08-03 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0009_bookinginfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='v_description',
            field=models.TextField(),
        ),
    ]
