# Generated by Django 4.0.3 on 2023-08-04 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0010_alter_vehicle_v_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookinginfo',
            old_name='b_date',
            new_name='b_bookdate',
        ),
        migrations.AddField(
            model_name='bookinginfo',
            name='b_returndate',
            field=models.DateTimeField(null=True),
        ),
    ]
